name: mood_trend_flutter
description: A new Flutter project.
publish_to: 'none'

version: 3.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  flutter_riverpod: ^2.4.4
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  package_info: ^2.0.2
  cloud_firestore: ^5.5.0
  hooks_riverpod: ^2.4.4
  flutter_hooks: ^0.20.3
  google_fonts: ^6.1.0
  flutter_localization: ^0.2.2
  gap: ^3.0.1
  url_launcher: ^6.1.14
  hexcolor: ^3.0.1
  syncfusion_flutter_charts: ^27.2.2
  intl: 0.19.0
  flutter_overboard: ^3.1.1
  shared_preferences: ^2.3.4
  flutter_launcher_icons: ^0.14.1
  json_annotation: ^4.8.1
  animated_checkmark: ^3.1.0
  flutter_native_splash: ^2.3.7
  tutorial_coach_mark: ^1.2.12
  google_mobile_ads: ^5.2.0
  firebase_analytics: ^11.3.6
  flutter_local_notifications: ^19.0.0
  timezone: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter_native_splash:
  color: '#FFFFFF'
  image: 'assets/logo.png'
  color_dark: '#FFFFFF'
  image_dark: 'assets/logo.png'
  fullscreen: true
  android_12:
    icon_background_color: '#FFFFFF'
    image: 'assets/android12_logo.png'
    icon_background_color_dark: '#FFFFFF'
    image_dark: 'assets/android12_logo.png'

flutter:
  generate: true

  uses-material-design: true
  assets:
    - assets/
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
flutter_intl:
  enabled: true
