// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj3ft_viT_PbQR1zpjZkOddEOWv3pTd9U',
    appId: '1:13191557999:web:62cde211b54d6873972e9a',
    messagingSenderId: '13191557999',
    projectId: 'mood-trend-prod',
    authDomain: 'mood-trend-prod.firebaseapp.com',
    storageBucket: 'mood-trend-prod.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQeX2L3Oi6nfIzjpF4yy5w_y0fHKxog3Y',
    appId: '1:13191557999:android:0922d14d5ab3733a972e9a',
    messagingSenderId: '13191557999',
    projectId: 'mood-trend-prod',
    storageBucket: 'mood-trend-prod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHU5zQPPkEJiEF25qmRO_jHQk4HDrOdvw',
    appId: '1:13191557999:ios:1b97dd6d0cd2e144972e9a',
    messagingSenderId: '13191557999',
    projectId: 'mood-trend-prod',
    storageBucket: 'mood-trend-prod.appspot.com',
    iosBundleId: 'com.moodtrend.moodTrendFlutter.RunnerTests',
  );
}
