// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3Ia0MeW0gb8gLDdITcE2EPGkxUe1Oegw',
    appId: '1:459351348535:web:4cab1601997e1487ca36b2',
    messagingSenderId: '459351348535',
    projectId: 'mood-trend-dev',
    authDomain: 'mood-trend-dev.firebaseapp.com',
    storageBucket: 'mood-trend-dev.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdYE2hMX5jM5O0_eC6Xg64O_9kpOIBb40',
    appId: '1:459351348535:android:e3c464e50a0b3f71ca36b2',
    messagingSenderId: '459351348535',
    projectId: 'mood-trend-dev',
    storageBucket: 'mood-trend-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4K4Bm530-hu3XrAo2OMg1aO1lX0oisoc',
    appId: '1:459351348535:ios:cf3e0b119538c536ca36b2',
    messagingSenderId: '459351348535',
    projectId: 'mood-trend-dev',
    storageBucket: 'mood-trend-dev.appspot.com',
    iosBundleId: 'com.moodtrend.moodTrendFlutter.RunnerTests',
  );
}
